import { Platform, StyleSheet } from 'react-native';
import { purple, deepPurple, ink, muted, lavender } from '../../theme/colors';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#FFFFFF' },
  scrollContent: { flexGrow: 1 },
  page: { width: '100%', maxWidth: 1180, alignSelf: 'center', paddingHorizontal: 24, paddingBottom: 24 },
  navbar: { minHeight: 88, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 16 },
  brand: { flexDirection: 'row', alignItems: 'center', gap: 9 },
  brandMark: { width: 34, height: 34, borderRadius: 11, backgroundColor: ink, alignItems: 'center', justifyContent: 'center' },
  brandMarkText: { color: '#FFFFFF', fontWeight: '800', fontSize: 18 },
  brandName: { fontSize: 20, fontWeight: '800', color: ink, letterSpacing: -0.5 },
  navLinks: { flexDirection: 'row-reverse', gap: 28, alignItems: 'center' },
  navLink: { color: muted, fontSize: 14, fontWeight: '600' },
  outlineButton: { borderWidth: 1, borderColor: '#D9D3DE', borderRadius: 10, paddingHorizontal: 15, paddingVertical: 10 },
  outlineButtonText: { color: ink, fontSize: 13, fontWeight: '700' },
  hero: { minHeight: 510, flexDirection: 'row-reverse', alignItems: 'center', justifyContent: 'space-between', gap: 60, paddingVertical: 48 },
  heroCompact: { flexDirection: 'column', alignItems: 'stretch', gap: 34, paddingVertical: 32 },
  heroCopy: { flex: 1, maxWidth: 550, alignItems: 'flex-end' },
  heroCopyCompact: { maxWidth: undefined },
  eyebrow: { flexDirection: 'row-reverse', alignItems: 'center', gap: 7, backgroundColor: lavender, borderRadius: 30, paddingHorizontal: 11, paddingVertical: 7 },
  eyebrowDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: purple },
  eyebrowText: { color: deepPurple, fontSize: 12, fontWeight: '800' },
  heroTitle: { color: ink, fontSize: 55, lineHeight: 65, fontWeight: '900', letterSpacing: -2.5, textAlign: 'right', marginTop: 19, writingDirection: 'rtl' },
  heroDescription: { color: muted, fontSize: 17, lineHeight: 29, textAlign: 'right', marginTop: 16, writingDirection: 'rtl' },
  heroActions: { flexDirection: 'row-reverse', alignItems: 'center', gap: 20, marginTop: 27, width: '100%' },
  heroActionsCompact: { gap: 14 },
  primaryButton: { flexDirection: 'row-reverse', alignItems: 'center', gap: 9, backgroundColor: purple, paddingHorizontal: 19, paddingVertical: 15, borderRadius: 12 },
  primaryButtonText: { color: '#FFFFFF', fontSize: 14, fontWeight: '800' },
  arrow: { color: '#FFFFFF', fontSize: 19, fontWeight: '700' },
  textButton: { paddingVertical: 12 },
  textButtonText: { color: ink, fontSize: 14, fontWeight: '800' },
  trustRow: { flexDirection: 'row-reverse', gap: 7, alignItems: 'center', marginTop: 24, alignSelf: 'flex-end' },
  trustCheck: { width: 18, height: 18, borderRadius: 9, backgroundColor: '#E8DDFC', alignItems: 'center', justifyContent: 'center' },
  trustCheckText: { color: deepPurple, fontSize: 11, fontWeight: '900' },
  trustText: { color: muted, fontSize: 12, writingDirection: 'rtl' },
  previewShell: { flex: 1, minWidth: 300, maxWidth: 450, backgroundColor: '#FFFFFF', borderRadius: 22, borderWidth: 1, borderColor: '#E8E2EC', shadowColor: '#2A143C', shadowOffset: { width: 0, height: 17 }, shadowOpacity: 0.13, shadowRadius: 35, elevation: 8, overflow: 'hidden', transform: [{ rotate: Platform.OS === 'web' ? '-2deg' : '0deg' }] },
  previewTopbar: { minHeight: 48, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 18, borderBottomWidth: 1, borderBottomColor: '#F0ECF2' },
  previewDots: { flexDirection: 'row', gap: 5 },
  dot: { width: 7, height: 7, borderRadius: 4 },
  previewTopbarText: { color: muted, fontSize: 12, fontWeight: '700', writingDirection: 'rtl' },
  previewBody: { padding: 23 },
  previewGreeting: { color: ink, fontSize: 21, fontWeight: '900', textAlign: 'right', writingDirection: 'rtl' },
  previewSubtitle: { color: muted, fontSize: 12, textAlign: 'right', marginTop: 4, writingDirection: 'rtl' },
  focusCard: { marginTop: 20, backgroundColor: ink, borderRadius: 15, padding: 17, flexDirection: 'row-reverse', justifyContent: 'space-between', alignItems: 'center' },
  focusLabel: { color: '#CFC6D5', fontSize: 11, fontWeight: '700', textAlign: 'right', writingDirection: 'rtl' },
  focusTitle: { color: '#FFFFFF', fontSize: 15, fontWeight: '900', marginTop: 6, textAlign: 'right', writingDirection: 'rtl' },
  focusCourse: { color: '#BEA3F6', fontSize: 11, marginTop: 3, textAlign: 'right', writingDirection: 'rtl' },
  playButton: { width: 36, height: 36, borderRadius: 18, backgroundColor: purple, alignItems: 'center', justifyContent: 'center' },
  playIcon: { color: '#FFFFFF', fontSize: 13, marginLeft: 2 },
  previewStats: { flexDirection: 'row-reverse', justifyContent: 'space-between', marginTop: 17, gap: 8 },
  statBox: { flex: 1, backgroundColor: '#FBF9FC', borderRadius: 10, paddingVertical: 12, alignItems: 'center' },
  statValue: { color: ink, fontSize: 15, fontWeight: '900' },
  statLabel: { color: muted, fontSize: 10, marginTop: 3, writingDirection: 'rtl' },
  progressLabelRow: { flexDirection: 'row-reverse', justifyContent: 'space-between', marginTop: 20 },
  progressText: { color: ink, fontSize: 11, fontWeight: '800', writingDirection: 'rtl' },
  progressPercent: { color: purple, fontSize: 11, fontWeight: '900' },
  progressTrack: { height: 7, borderRadius: 10, backgroundColor: '#EAE5EE', marginTop: 8, overflow: 'hidden' },
  progressFill: { height: '100%', width: '68%', borderRadius: 10, backgroundColor: purple },
  sectionHeader: { alignItems: 'flex-end', marginTop: 35 },
  sectionKicker: { color: purple, fontSize: 12, fontWeight: '900', letterSpacing: 0.3, textAlign: 'right', writingDirection: 'rtl' },
  sectionTitle: { color: ink, fontSize: 34, lineHeight: 42, fontWeight: '900', letterSpacing: -1.2, textAlign: 'right', marginTop: 7, writingDirection: 'rtl' },
  featureGrid: { flexDirection: 'row-reverse', gap: 15, marginTop: 27 },
  featureGridCompact: { flexDirection: 'column' },
  journey: { backgroundColor: lavender, borderRadius: 20, marginTop: 72, padding: 31, flexDirection: 'row-reverse', justifyContent: 'space-between', alignItems: 'center', gap: 28 },
  journeyCompact: { flexDirection: 'column', alignItems: 'stretch' },
  journeyCopy: { flex: 0.9, alignItems: 'flex-end' },
  journeyTitle: { fontSize: 29, lineHeight: 36 },
  journeyDescription: { color: muted, fontSize: 14, lineHeight: 23, textAlign: 'right', marginTop: 9, writingDirection: 'rtl' },
  steps: { flex: 1.1, gap: 12 },
  step: { flexDirection: 'row-reverse', alignItems: 'center', gap: 11, minHeight: 32 },
  stepNumber: { width: 28, height: 28, borderRadius: 14, backgroundColor: '#FFFFFF', alignItems: 'center', justifyContent: 'center' },
  stepNumberText: { color: purple, fontSize: 12, fontWeight: '900' },
  stepText: { color: ink, fontSize: 14, fontWeight: '800', writingDirection: 'rtl' },
  stepLine: { position: 'absolute', right: 13, top: 27, height: 17, borderRightWidth: 1, borderRightColor: '#CDBBF4' },
  cta: { marginTop: 72, backgroundColor: ink, borderRadius: 20, paddingVertical: 46, paddingHorizontal: 30, alignItems: 'center' },
  ctaTitle: { color: '#FFFFFF', fontSize: 34, fontWeight: '900', letterSpacing: -1.1, writingDirection: 'rtl' },
  ctaDescription: { color: '#CFC6D5', maxWidth: 520, fontSize: 14, lineHeight: 23, textAlign: 'center', marginTop: 10, writingDirection: 'rtl' },
  lightButton: { marginTop: 22, backgroundColor: '#FFFFFF', paddingHorizontal: 19, paddingVertical: 14, borderRadius: 11 },
  lightButtonText: { color: ink, fontSize: 14, fontWeight: '900', writingDirection: 'rtl' },
  footer: { flexDirection: 'row-reverse', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 30 },
  footerBrand: { color: ink, fontSize: 15, fontWeight: '900' },
  footerText: { color: muted, fontSize: 12, writingDirection: 'rtl' },
});
